
name: Sync to Org

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Org repo
        run: |
          git remote add org https://x-access-token:${{ secrets.ORG_TOKEN }}@github.com/BF-D-challenge/make-own-product1.git
          git push org HEAD:refs/heads/members/${{ github.repository_owner }} --force